### ISSUE TITLE
yosys synthesis fails on MacOS: source file path passed twice → "Re-definition of module"

### ISSUE THREAD

**Issue by danielpourbakhsh** [one-ware/OneWare#240]
**Description**:
When running the FPGA synthesis flow (GHDL → yosys, iCE40 target), OneWare passes the generated Verilog file to yosys twice on the command line. yosys reads the file twice, which causes the top module to be defined twice and aborts with a Re-definition of module error.

````
[test]: ghdl -i --workdir=/Users/daniel/OneWareStudio/Projects/test/build -P/Users/daniel/OneWareStudio/Projects/test/build --std=93c test.vhd test_tb.vhd

[test]: ghdl -m --workdir=/Users/daniel/OneWareStudio/Projects/test/build -P/Users/daniel/OneWareStudio/Projects/test/build --std=93c test

[test]: ghdl -e --workdir=/Users/daniel/OneWareStudio/Projects/test/build -P/Users/daniel/OneWareStudio/Projects/test/build --std=93c test

[test]: ghdl --synth --std=93c --workdir=/Users/daniel/OneWareStudio/Projects/test/build -P/Users/daniel/OneWareStudio/Projects/test/build --out=verilog -o=/Users/daniel/OneWareStudio/Projects/test/build/gen_verilog/test.v test

[test]: yosys -q -p "synth_ice40 -json build/synth.json" /Users/daniel/OneWareStudio/Projects/test/build/gen_verilog/test.v /Users/daniel/OneWareStudio/Projects/test/build/gen_verilog/test.v
/Users/daniel/OneWareStudio/Projects/test/build/gen_verilog/test.v:1: ERROR: Re-definition of module `$abstract\test'!
````

**Environment:**
OS: macOS Tahoe 26.3.1 (a) (25D771280a)
OneWare Studio version: 1.0.16.0
OSS CAD Suite Extension: 2026.02.9 Github
yosys version from yosys -V: Yosys 0.62+55 (git sha1 29a270c4b-dirty, aarch64-apple-darwin23.5-clang++ 18.1.8 -fPIC -O3) if applicable
GHDL Extension: 5.1.1 Github

**Possible cause:**
This looks like the source file path ends up in the yosys argument list twice. A likely cause is how the command string / argument list is assembled — e.g. the file path is appended once when collecting source files and a second time when building the final yosys call, or a list of source files is concatenated with a wrong/empty separator so the same entry is duplicated. Passing each source file to yosys exactly once should fix it.

**Comment by hendrikmennen** [comment]
I am publishing an update where this is fixed. If you were using the VHDL to Verilog conversion from GHDL, please update the extension aswell and activate it in project settings.

<img width="553" height="441" alt="Image" src="https://github.com/user-attachments/assets/49fc16b4-f161-411b-92e1-40892b28d2a5" />

**Comment by danielpourbakhsh** [comment]
Thank you Hendrik for the quick action and the advice! 
After upgrading OWS from minor version 16 to 19, attempting to install GHDL 6.0.0 via Extensions → Binaries → GHDL (GitHub) fails with: `No compatible target found for package ghdl version 6.0.0.` Fallback to GHDL 5.1.1 results in an unresolved toolchain error: `Toolchain GHDL_Yosys not found` during Verilog pre-compilation. The issue persists after reinstalling GHDL 5.1.1 and restarting OWS. Also persists after restarting the OS.
